name: Build test

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: build on x86
      run: |
        ls -a /usr/src/
        sudo apt update 
        sudo apt install -y build-essential
        mkdir -p /opt/additionalFiles
        make ARCH=x86 CROSS_COMPILE= -C /usr/src/linux-headers-6.5.0-1016-azure M=/opt/additionalFiles modules
        ls