name: Build test

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install dependencies
      run: |
        sudo apt install -y ruby-dev
        sudo gem install fpm

    - name: build on x86
      run: |
        sudo mkdir -p /lib/modules/6.2.0-1018-azure/kernel/drivers/net/wireless/
        sudo apt update 
        sudo apt install -y build-essential tree
        chmod +x install-driver.sh
        sudo ./install-driver.sh
        # make
        ls